model:
  type: xgboost
  params:
    n_estimators: 200
    max_depth: 5
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42

split:
  test_size: 0.2
  random_state: 42
  stratify: true

evaluation:
  metrics:
    - auc
    - accuracy
    - precision
    - recall
    - f1
